// <auto-generated />
using System;
using DeliveryYaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliveryYaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118001408_MetodoPagoPermitidoComercio")]
    partial class MetodoPagoPermitidoComercio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cliente", b =>
                {
                    b.Property<int>("idcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idcliente"));

                    b.Property<string>("calle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("calle");

                    b.Property<string>("celular")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("celular");

                    b.Property<string>("ciudad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<DateTime>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("dni")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("nacimiento")
                        .HasColumnType("date")
                        .HasColumnName("nacimiento");

                    b.Property<string>("nombreCompleto")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombreCompleto");

                    b.Property<int>("numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<DateTime>("updatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("idcliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Admin", b =>
                {
                    b.Property<int>("idadmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idadmin"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("idadmin");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Categoria", b =>
                {
                    b.Property<int>("idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcategoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idcategoria"));

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("nombre")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("updatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("idcategoria");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("CategoriaIdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria_idcategoria");

                    b.Property<int>("ProductoIdProducto")
                        .HasColumnType("int")
                        .HasColumnName("producto_idproducto");

                    b.HasKey("CategoriaIdCategoria", "ProductoIdProducto");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("categoria_has_producto", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Comercio", b =>
                {
                    b.Property<int>("idcomercio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcomercio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idcomercio"));

                    b.Property<string>("alias")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("alias");

                    b.Property<string>("calle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("calle");

                    b.Property<string>("celular")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("celular");

                    b.Property<string>("ciudad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<decimal>("comision")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("comision");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<string>("cvu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cvu");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<bool?>("deliveryPropio")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deliveryPropio");

                    b.Property<bool>("destacado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("destacado");

                    b.Property<string>("email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("encargado")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("encargado");

                    b.Property<decimal>("envio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("envio");

                    b.Property<string>("eslogan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("eslogan");

                    b.Property<string>("fotoPortada")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("fotoPortada");

                    b.Property<decimal?>("latitud")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("longitud")
                        .HasColumnType("decimal(10,6)")
                        .HasColumnName("longitud");

                    b.Property<string>("nombreComercio")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombreComercio");

                    b.Property<int>("numero")
                        .HasColumnType("int")
                        .HasColumnName("numero");

                    b.Property<bool?>("pagoEfectivo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pagoEfectivo");

                    b.Property<bool?>("pagoTarjeta")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pagoTarjeta");

                    b.Property<bool?>("pagoTransferencia")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pagoTransferencia");

                    b.Property<string>("password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("sucursales")
                        .HasColumnType("int")
                        .HasColumnName("sucursales");

                    b.Property<string>("tipoComercio")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipoComercio");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("idcomercio");

                    b.ToTable("comercio", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.ComercioCategoria", b =>
                {
                    b.Property<int>("ComercioIdComercio")
                        .HasColumnType("int")
                        .HasColumnName("comercio_idcomercio");

                    b.Property<int>("CategoriaIdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("categoria_idcategoria");

                    b.HasKey("ComercioIdComercio", "CategoriaIdCategoria");

                    b.HasIndex("CategoriaIdCategoria");

                    b.ToTable("comercio_has_categoria", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.ComercioHorario", b =>
                {
                    b.Property<int>("ComercioIdComercio")
                        .HasColumnType("int")
                        .HasColumnName("comercio_idcomercio");

                    b.Property<int>("HorariosIdHorarios")
                        .HasColumnType("int")
                        .HasColumnName("horarios_idhorarios");

                    b.HasKey("ComercioIdComercio", "HorariosIdHorarios");

                    b.HasIndex("HorariosIdHorarios");

                    b.ToTable("comercio_has_horarios", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.EstadoPedido", b =>
                {
                    b.Property<int>("idestado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idestado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idestado"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("idestado");

                    b.ToTable("estado_pedido", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Horarios", b =>
                {
                    b.Property<int>("idhorarios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idhorarios");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idhorarios"));

                    b.Property<bool>("abierto")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("abierto");

                    b.Property<TimeSpan?>("apertura")
                        .HasColumnType("time")
                        .HasColumnName("apertura");

                    b.Property<TimeSpan?>("cierre")
                        .HasColumnType("time")
                        .HasColumnName("cierre");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<string>("dias")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dias");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updatedAt");

                    b.HasKey("idhorarios");

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.ItemPedido", b =>
                {
                    b.Property<int>("iditemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iditemPedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("iditemPedido"));

                    b.Property<int>("ComercioIdComercio")
                        .HasColumnType("int");

                    b.Property<int>("PedidoIdPedido")
                        .HasColumnType("int");

                    b.Property<int>("ProductoIdProducto")
                        .HasColumnType("int");

                    b.Property<int>("cantProducto")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime");

                    b.Property<decimal>("precioFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("iditemPedido");

                    b.HasIndex("ComercioIdComercio");

                    b.HasIndex("PedidoIdPedido");

                    b.HasIndex("ProductoIdProducto");

                    b.ToTable("item_pedido", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.MetodoPagoPedido", b =>
                {
                    b.Property<int>("idmetodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idmetodo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idmetodo"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("metodo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("idmetodo");

                    b.ToTable("metodo_pago_pedido", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Pedido", b =>
                {
                    b.Property<int>("idpedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idpedido"));

                    b.Property<int>("ClienteIdCliente")
                        .HasColumnType("int")
                        .HasColumnName("cliente_idcliente");

                    b.Property<int>("EstadoPedidoIdEstado")
                        .HasColumnType("int")
                        .HasColumnName("estadopedido_idestado");

                    b.Property<int>("MetodoPagoPedidoIdMetodo")
                        .HasColumnType("int")
                        .HasColumnName("metodoPagoPedido_idmetodo");

                    b.Property<string>("codigo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("comercioRepartidor")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("direccionEnvio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan>("hora")
                        .HasColumnType("time");

                    b.Property<bool>("pagado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("subtotalPedido")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("idpedido");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("EstadoPedidoIdEstado");

                    b.HasIndex("MetodoPagoPedidoIdMetodo");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Producto", b =>
                {
                    b.Property<int>("idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idproducto"));

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("fotoPortada")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("oferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<decimal>("precioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("unidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("idproducto");

                    b.ToTable("producto", (string)null);
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.TarifaRepartidorLibre", b =>
                {
                    b.Property<int>("idtarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idtarifa"));

                    b.Property<int>("RepartidorIdRepartidor")
                        .HasColumnType("int")
                        .HasColumnName("repartidor_idrepartidor");

                    b.Property<int>("cantPedidos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("kmRecorridos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("tarifaBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idtarifa");

                    b.HasIndex("RepartidorIdRepartidor");

                    b.ToTable("tarifaRepartidorLibre");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Vehiculo", b =>
                {
                    b.Property<int>("idvehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idvehiculo"));

                    b.Property<string>("companiaSeguros")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("patente")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("seguro")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("idvehiculo");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Repartidor", b =>
                {
                    b.Property<int>("idrepartidor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idrepartidor"));

                    b.Property<string>("calle")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("cantPedidos")
                        .HasColumnType("int");

                    b.Property<string>("celular")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ciudad")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("cvu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("libreRepartidor")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("puntuacion")
                        .HasColumnType("decimal(10,1)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("vehiculoIdVehiculo")
                        .HasColumnType("int");

                    b.HasKey("idrepartidor");

                    b.HasIndex("vehiculoIdVehiculo");

                    b.ToTable("repartidor");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.CategoriaProducto", b =>
                {
                    b.HasOne("DeliveryYaBackend.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.ComercioCategoria", b =>
                {
                    b.HasOne("DeliveryYaBackend.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaIdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioIdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Comercio");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.ComercioHorario", b =>
                {
                    b.HasOne("DeliveryYaBackend.Models.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioIdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.Horarios", "Horarios")
                        .WithMany()
                        .HasForeignKey("HorariosIdHorarios")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.ItemPedido", b =>
                {
                    b.HasOne("DeliveryYaBackend.Models.Comercio", "Comercio")
                        .WithMany()
                        .HasForeignKey("ComercioIdComercio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.Pedido", "Pedido")
                        .WithMany("ItemsPedido")
                        .HasForeignKey("PedidoIdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoIdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comercio");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Pedido", b =>
                {
                    b.HasOne("Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.EstadoPedido", "EstadoPedido")
                        .WithMany()
                        .HasForeignKey("EstadoPedidoIdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryYaBackend.Models.MetodoPagoPedido", "MetodoPagoPedido")
                        .WithMany()
                        .HasForeignKey("MetodoPagoPedidoIdMetodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("EstadoPedido");

                    b.Navigation("MetodoPagoPedido");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.TarifaRepartidorLibre", b =>
                {
                    b.HasOne("Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorIdRepartidor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Repartidor", b =>
                {
                    b.HasOne("DeliveryYaBackend.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("vehiculoIdVehiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("DeliveryYaBackend.Models.Pedido", b =>
                {
                    b.Navigation("ItemsPedido");
                });
#pragma warning restore 612, 618
        }
    }
}
